//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpNBT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpNBT.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-detect is not a valid compression type when writing..
        /// </summary>
        internal static string AutoDetectNotValid {
            get {
                return ResourceManager.GetString("AutoDetectNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect compression type..
        /// </summary>
        internal static string CannotDetectCompression {
            get {
                return ResourceManager.GetString("CannotDetectCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is not opened for reading..
        /// </summary>
        internal static string CannotReadStream {
            get {
                return ResourceManager.GetString("CannotReadStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is not opened for writing..
        /// </summary>
        internal static string CannotWriteStream {
            get {
                return ResourceManager.GetString("CannotWriteStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child tag in collection cannot be null..
        /// </summary>
        internal static string ChildCannotBeNull {
            get {
                return ResourceManager.GetString("ChildCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children of this collection type must be named..
        /// </summary>
        internal static string ChildrenMustBeNamed {
            get {
                return ResourceManager.GetString("ChildrenMustBeNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children of this collection type cannot be named..
        /// </summary>
        internal static string ChildrenMustNotBeNamed {
            get {
                return ResourceManager.GetString("ChildrenMustNotBeNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect tag type added to this collection..
        /// </summary>
        internal static string ChildWrongType {
            get {
                return ResourceManager.GetString("ChildWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC validation failed..
        /// </summary>
        internal static string CRCFail {
            get {
                return ResourceManager.GetString("CRCFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format cannot be both big and little endian.
        /// </summary>
        internal static string FormatBothBigEndianAndLittleEndian {
            get {
                return ResourceManager.GetString("FormatBothBigEndianAndLittleEndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format must be either big or little endian.
        /// </summary>
        internal static string FormatNeitherBigEndianNorLittleEndian {
            get {
                return ResourceManager.GetString("FormatNeitherBigEndianNorLittleEndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An EndTag is not a valid child type for a non-empty ListTag..
        /// </summary>
        internal static string InvalidEndTagChild {
            get {
                return ResourceManager.GetString("InvalidEndTagChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative length specified..
        /// </summary>
        internal static string NegativeLengthSpecified {
            get {
                return ResourceManager.GetString("NegativeLengthSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown tag type..
        /// </summary>
        internal static string UnknownTagType {
            get {
                return ResourceManager.GetString("UnknownTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decode value from bytes..
        /// </summary>
        internal static string VarIntCannotDecode {
            get {
                return ResourceManager.GetString("VarIntCannotDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value too large to be stored in a {0} integer..
        /// </summary>
        internal static string VarIntTooMuchData {
            get {
                return ResourceManager.GetString("VarIntTooMuchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element.
        /// </summary>
        internal static string WordElement {
            get {
                return ResourceManager.GetString("WordElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elements.
        /// </summary>
        internal static string WordElements {
            get {
                return ResourceManager.GetString("WordElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        internal static string WordEntries {
            get {
                return ResourceManager.GetString("WordEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entry.
        /// </summary>
        internal static string WordEntry {
            get {
                return ResourceManager.GetString("WordEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported stream..
        /// </summary>
        internal static string ZlibUnsupported {
            get {
                return ResourceManager.GetString("ZlibUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be greater than 15..
        /// </summary>
        internal static string ZLibValueGreater15 {
            get {
                return ResourceManager.GetString("ZLibValueGreater15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be greater than 31..
        /// </summary>
        internal static string ZLibValueGreater31 {
            get {
                return ResourceManager.GetString("ZLibValueGreater31", resourceCulture);
            }
        }
    }
}
